#!/bin/sh

. /usr/lib/live/config.sh

Init ()
{
	if component_was_executed "anemone-live-password"
	then
		exit 0
	fi

	echo -n " anemone-live-password"
}

Config ()
{
	if ! getent passwd anemone >/dev/null
	then
		echo "Anemone live user was not created" >&2
		exit 1
	fi

	printf '%s:%s\n' "anemone" "anemone" | chpasswd
	touch /var/lib/live/config/anemone-live-password
}

Init
Config
